dat<-read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?")
dat$Date_Time<-paste(dat$Date, dat$Time)
dat$Date_Time<-strptime(dat$Date_Time, "%d/%m/%Y %H:%M:%S")
dat$Date<-strptime(dat$Date, "%d/%m/%Y")
dat$Date<-as.Date(dat$Date)
dat1<-subset(dat, Date==as.Date("2007-02-01"))
dat2<-subset(dat, Date==as.Date("2007-02-02"))
dat3<-rbind(dat1,dat2)
png(filename="plot1.png", width = 480, height = 480, units = "px")
hist(dat3$Global_active_power, col="red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()